### PR TITLE
please use docker compose v2

### PR DESCRIPTION
**Pull request by aogier**
docker compose v1 is EOL since june 2023 https://docs.docker.com/compose/migrate/

### CODE REVIEW

**Comment by aogier** [comment]
mmh, are you sure this unpolite path is what you want to follow?

**Comment by aogier** [comment]
let's give you another chance

**Comment by aogier** [comment]
@u238 pinging you just because this looks like an atomic friction and after PR's title rename yeah, let's make it an atomic royal rumble

**Comment by aogier** [comment]
(which was public from its opening, so let's thunderdome: Two men enter, one man leave! :D 
image

**Comment by aogier** [comment]
so an humble title like "use docker compose v2" does not work because _reasons_, let's hope for a more aggressive one like "please use docker compose v2 and stop being ignorant about EOL" because my feeling is a lot of people base their stability on this software stability

**Review by mcodato — APPROVED** [review]

**Pull request closed without merging**
